---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: httpd
      ports:
        - containerPort: 80
    - name: tomcat-container
      image: tomcat
      ports:
        - containerPort: 8080
...

---
apiVersion: v1 
kind: service
metadata: 
  name: my-sevrice
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
...